site_name: STOBG Data Analytics Documentation
repo_url: https://github.com/STOBG-Data-and-Analytics/cmic-project-analytics-docs
theme: 
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/sto_icon.png
  pallete:
    scheme: slate
  features:
    - navigation.expand
    - navigation.instant
    - content.code.copy

nav:
  - Home: index.md
  - Vision:
    - General: vision/index.md
  - Product Management:
    - General: product/general.md
    - Data Dictionary: product/data-dictionary.md
    - Source-to-Target Data Mapping: product/source-to-target-map.md
  - Business Analysis:
    - General: business-analysis/business-analysis.md
    - Conceptual Data Model: business-analysis/conceptual-data-model.md
  - Project Management:
    - Delivery Process Overview: project-management/process.md
    - Issue Tracking (Jira): project-management/issue-tracking-jira.md
    - Change Management: project-management/change-management-process.md
    - Release Management: project-management/release-it.md
    - Release Plan: project-management/release-plan.md
    - Communication Plan: project-management/communication-plan.md
    - Sprint Review Log: project-management/sprint-reviews.md
    - Retrospectives Log: project-management/retrospectives.md
  - BI:
    - General: bi/index.md
  - Data Science:
    - General: data-science/index.md
  - Data Products:
    - General: data-products/index.md
    - Project Performance Analytics (CMIC): data-products/perf-analytics.md
    - Safety: data-products/safety.md
  - Data Governance:
    - General: data-governance/index.md
  - Technology:
    - Architecture: tech/architecture.md
    - CI/CD Process: tech/ci-cd.md
    - Engx: tech/engx.md
    - KPI/Benchmarks Design: tech/kpi-benchmarks-design.md
    - GC Forecast Report Design: tech/gc-forecast-report-design.md
    - Workato Integration: tech/workato-integration.md
    - Origami Integration: tech/origami-integration.md
  - Quality Assurance:
    - General: quality-assurance/index.md
    - Test Strategy: quality-assurance/test-strategy.md
    - "Test Plan: Trade Spend": quality-assurance/trade-spend-test-plan.md
    - "Test Plan: Safety": quality-assurance/safety-test-plan.md
    - "Test Plan: Project KPIs/Benchmark": quality-assurance/test-plan-benchmarks.md
    - "Test Report: Project KPIs/Benchmark": quality-assurance/test-reports/test-report-benchmarks.md
    - "Test Report: General": quality-assurance/test-reports/index.md
    - "Test Report: Tools for Reporting": quality-assurance/test-reports/tool-for-reports.md
    - "Test Report: Submittals": quality-assurance/test-reports/test-report-submittal.md
    - "Test Report: TECH Sprint 2024.1": quality-assurance/test-reports/test-report-tech-2024-1.md
  - Team:
    - General: team/index.md
    - Policies & Agreements: team/policies.md
    - Onboarding: team/onboarding.md
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search:
      lang: en
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      # bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/assets/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - glightbox
  - drawio_file
  - table-reader
  - print-site
