site_name: Documentation as a Code Blueprint
repo_url: https://github.com/yevgen-ponomarenko/doc-as-code-blueprint/
theme: 
  name: material
  logo: assets/images/logo.png
  # favicon: assets/images/sto_icon.png
  pallete:
    scheme: slate
  features:
    - navigation.expand
    - navigation.instant
    - content.code.copy

nav:
  - Home: index.md
  - Project Management:
    - Change Management: project-management/change-management-process.md
  - About: about.md
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search:
      lang: en
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      # bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/assets/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - glightbox
  - drawio_file
  - table-reader
  - print-site
