# This workflow will build, test and deploy the documentation site built on MkDocs 
# to the gh-pages branch on every push to the main branch.
#
name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and Test
        run: |
          mkdocs build --verbose --clean --strict
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
         

