
# This workflow will build and test on syntax errors the documentation site's code built on MkDocs 

name: Build Documentation Site

on:
  pull_request:
    paths: 
      - 'docs/**'
    branches:
      - 'main'

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and Test
        run: |
          mkdocs build --verbose --clean --strict